
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: nginx
    image: httpd:latest
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    ports:
    - containerPort: 80